apiVersion: v1
kind: Pod
metadata:
  name: http-echo-server
  namespace: cattle-logging-system
  labels:
    app: http-echo-server
spec:
  containers:
  - name: http-echo
    image: mendhak/http-https-echo:latest
    ports:
    - containerPort: 8080
      name: http
    env:
      # Optional: Disable default ExpressJS log lines to reduce noise if you only care about the detailed JSON output
      # - name: DISABLE_REQUEST_LOGS
      #   value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: http-echo-service
  namespace: cattle-logging-system
spec:
  selector:
    app: http-echo-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
