apiVersion: logging.banzaicloud.io/v1beta1
kind: FluentbitAgent
metadata:
  name: rancher-logging-root
  namespace: cattle-logging-system
spec:
  metrics:
    prometheusRules: false
    serviceMonitor: false
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    value: "true"
  - effect: NoExecute
    key: node-role.kubernetes.io/etcd
    value: "true"
